openapi: 3.0.3
info:
  title: Gym CRM API
  version: 1.0.0
  description: REST API for trainee and trainer registration

servers:
  - url: http://localhost:8080

paths:
  /trainees/register:
    post:
      summary: Register a new trainee
      operationId: registerTrainee
      tags:
        - Trainee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/trainee.yaml#/TraineeCreateRequest'

      responses:
        '200':
          description: Trainee successfully registered
          content:
            application/json:
              schema:
                $ref: './components/schemas/trainee.yaml#/TraineeRegistrationResponse'
components: { }
