spring:
  datasource:
    url: jdbc:h2:file:./data/gym-crm-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true

logging:
  level:
    root: DEBUG
