server:
  port: 8080

spring:
  application:
    name: "Gym CRM"

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm_db
    driver-class-name: org.postgresql.Driver
    username: gym
    password: gym

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl.auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    contexts: dev
    drop-first: false