server:
  port: 8080

project:
  name: "Gym CRM"
  version: "1.0"

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/gym_crm_db
  username: gym
  password: gym

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: validate

storage:
  filePath: src/main/resources/storage.json

liquibase:
  change-log: classpath:db/changelog/changelog-master.xml
  enabled: true
  contexts: dev
  drop-first: false

