server:
  port: 8080

project:
  name: "Gym CRM"
  version: "1.0"

database:
  driver: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  username: sa
  password:

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: create-drop

storage:
  filePath: src/main/resources/storage.json

liquibase:
  enabled: false
