spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.gcs.app: DEBUG
